# Generated by Django 5.2 on 2025-04-25 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                related_name="cars_driven", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
